In [1]:
import numpy as np

In [2]:
arr =  np.array([2,4,5])
print(arr,type(arr))

[2 4 5] <class 'numpy.ndarray'>


In [3]:
print("Shape of the array : " ,arr.shape)


Shape of the array :  (3,)


In [4]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2,type(arr2))
print("shape off arr2 : ",arr2.shape)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>
shape off arr2 :  (2, 4)


In [5]:
arr2[0,1]

2

In [6]:
arr3D = np.array([
    [
        [1,2,3],
        [5,6,7],
        [3,4,5]
    ],
    [
        [1,2,3],
        [5,6,7],
        [3,4,5]
    ],
    [
        [1,2,3],
        [5,6,7],
        [3,4,5]
    ]
])

print(arr3D)
print(arr3D[0,1,2])

[[[1 2 3]
  [5 6 7]
  [3 4 5]]

 [[1 2 3]
  [5 6 7]
  [3 4 5]]

 [[1 2 3]
  [5 6 7]
  [3 4 5]]]
7


In [7]:
zeros = np.zeros((4,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
ones = np.ones(3,)
print(ones)

[1. 1. 1.]


In [9]:
consts = np.full((3,3),3)
print(consts)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [10]:
rand = np.random.random((4,4))
rand

array([[0.89306526, 0.21903444, 0.41639378, 0.50748857],
       [0.32954612, 0.88936502, 0.8757291 , 0.61614802],
       [0.06332322, 0.21821317, 0.87547155, 0.74771898],
       [0.3041213 , 0.39026836, 0.41261664, 0.67982659]])

In [11]:
ar = np.array([
    [2,3,4],
    [5,6,7],
    [8,9,0]
])

ar[:2]
#ar[:2,1:3]

array([[2, 3, 4],
       [5, 6, 7]])

In [12]:
a = np.array([
    [2,3,4,5],
    [5,6,7,8],
    [8,9,0,1]
])
a[2,0:2]#last row col1 col2

array([8, 9])

In [13]:
a[1,:]#row 2

array([5, 6, 7, 8])

In [14]:
a[:,2:3]#third column

array([[4],
       [7],
       [0]])

In [15]:
a[:,0:2]#extract col1 & col2

array([[2, 3],
       [5, 6],
       [8, 9]])

In [16]:
ab = np.array([
    [2,3,4,5],
    [5,6,7,8],
    [8,9,0,1]
])
ab

array([[2, 3, 4, 5],
       [5, 6, 7, 8],
       [8, 9, 0, 1]])

In [17]:
bool_idx = [ab>3]
bool_idx

[array([[False, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True, False, False]])]

In [18]:
ab[ab>3]

array([4, 5, 5, 6, 7, 8, 8, 9])

In [19]:
x =  np.array([
    [1,2],
    [3,4]
])
y =  np.array([
    [5,6],
    [7,8]
])

x+y

array([[ 6,  8],
       [10, 12]])

In [20]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [21]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [22]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [23]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [24]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [25]:
v= np.array([4,5])
w = np.array([3,6])

print(v.dot(w))

42


In [26]:
np.dot(v,w)

42

In [27]:
np.dot(x,y)#dot product

array([[19, 22],
       [43, 50]])

In [28]:
arr2.T#transpose

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [29]:
np.sum(arr2)

36

In [30]:
np.sum(arr2,axis=0)#sum of each col

array([ 6,  8, 10, 12])

In [31]:
np.sum(arr2,axis=1)#sum of each row

array([10, 26])

In [32]:
u = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

s = np.array([1,0,1])

t = np.empty_like(u)
t

array([[   4128860,    6029375,    3801155],
       [   5570652,    6619251,    7536754],
       [1616510976,        525,    3604528]])

In [33]:
for i in range(len(u)):#for loop approach to vector v in every coloumn
    t[i,:] = u[i,:]+s
t

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [34]:
#mathematical approach
stacked_v = np.tile(s,(3,1))
print(stacked_v)

[[1 0 1]
 [1 0 1]
 [1 0 1]]


In [35]:
u+stacked_v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [36]:
u+s

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [37]:
arr2.reshape((4,2))#reshape

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])